Adding footer header with cms
ecomplus/storefront-starter pull request #5
Opened 2019-05-14 16:50 UTC by vitorrgg

2019-05-14 17:45 UTC, leomp12 requested changes

2019-05-14 17:45 UTC, leomp12 commented on content/pages/2019-05-13-sobre-nós.json
> +{
File names in English, never with accents.

2019-05-14 17:45 UTC, leomp12 commented on template/views/partials/templates/footer.ejs
> +          <% for (var page in extra_pages)  {%>
must check the object property inside loop:
```javascript
for (var page in extra_pages)  {
  if (extra_pages.hasOwnProperty[page]) {
    // do the stuff..
  }
}
```

2019-05-14 17:45 UTC, leomp12 commented on template/views/partials/templates/header.ejs
> +            <a href="<%- page.link %>">
wrong indentation here...

2019-05-14 17:45 UTC, leomp12 commented on template/views/partials/templates/header.ejs
> +            <a href="<%- page.link %>">
missing spaces before link tag (inside loop)

2019-05-14 17:48 UTC, leomp12 commented
You're referring `extra_pages`, but the file is saved as [`content/extra-pages`](https://github.com/ecomclub/storefront/blob/664d97490b1a4f0e9a97eb09bee647cb5a43a617/template/public/admin/config.yml#L44), so on template params the object is available as `extra-pages`, not `extra_pages`.

2019-05-14 17:49 UTC, leomp12 commented
Deploy failed with
```
TypeError: Cannot read property \'title\' of undefined\n \n - index.ejs:98
```

2019-05-14 19:10 UTC, vitorrgg commented on content/pages/2019-05-13-sobre-nós.json
> +{
Deafault extra_page file name have page title in it, some times it will be in portuguese. Change that?

2019-05-14 19:20 UTC, leomp12 commented on content/pages/2019-05-13-sobre-nós.json
> +{
Not title, but `slug`...
There's a [`clear_accents`](https://www.netlifycms.org/docs/configuration-options/#slug-type) config option, it should work, if not, you may edit the collection slug pattern [here](https://github.com/ecomclub/storefront/blob/664d97490b1a4f0e9a97eb09bee647cb5a43a617/template/public/admin/config.yml#L47).

2019-05-14 20:40 UTC, leomp12 requested changes

2019-05-14 20:40 UTC, leomp12 commented on template/views/partials/templates/header.ejs
> +          <% layout.header.contacts_stripe.pages.forEach(page => {%>
should be:
```ejs
          <% if (layout.header.contacts_stripe.pages) { %>
            <% layout.header.contacts_stripe.pages.forEach(page => {%>
              <a href="<%- page.link %>">
                <%- page.title %>
              </a>
            <% }) %>
          <% } %>
```

2019-05-15 18:30 UTC, leomp12 approved these changes

2019-05-15 18:30 UTC, merged