Footer header
ecomplus/storefront-starter pull request #7
Opened 2019-05-16 16:14 UTC by vitorrgg

Creating contacts page on, so user does not have to insert contact info more than one time

2019-05-16 16:40 UTC, leomp12 requested changes

2019-05-16 16:40 UTC, leomp12 commented on README.md
> +[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?stack=cms&repository=https://github.com/vitorrgg/storefront)
please don't change the repo on netlify deploy button

2019-05-16 16:40 UTC, leomp12 commented on content/blog_posts/2019_05_16_esta-loja-é-um-progressive-web-app.json
> +"body": "Quais são as vantagens?\r\n\nRetenção e economia são as principais vantagens do PWA. Normalmente, ao utilizar um aplicativo o usuário segue um passo a passo – pode variar entre: buscar o app
indentation is wrong here

2019-05-16 16:49 UTC, vitorrgg commented on README.md
> +[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?stack=cms&repository=https://github.com/vitorrgg/storefront)
Check

2019-05-17 15:15 UTC, leomp12 approved these changes

2019-05-17 15:15 UTC, merged